_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 14
                - 16
                - 55
            "4": 3.12.3
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 256
d_model:
    value: 64
dim_feedforward:
    value: 512
dropout:
    value: 0.14960594487495826
early_stopping_patience:
    value: 10
epochs:
    value: 100
input_seq_len:
    value: 48
learning_rate:
    value: 0.00070408684750718
nhead:
    value: 4
num_decoder_layers:
    value: 2
num_encoder_layers:
    value: 4
output_seq_len:
    value: 24
pretrain_data_prefix:
    value: data/transfer_learning_data/
pv_files:
    value:
        - PV Plants Datasets_62030198.csv
        - PV Plants Datasets_62032213.csv
        - PV Plants Datasets_73060645.csv
        - PV Plants Datasets_73061935.csv
        - PV Plants Datasets_84071566.csv
        - PV Plants Datasets_84071567.csv
        - PV Plants Datasets_84071568.csv
        - PV Plants Datasets_84071569.csv
        - PV Plants Datasets_84071570.csv
pv_peak_power_kwp:
    value:
        - 22400
        - 22400
        - 22400
        - 22400
        - 22400
        - 22400
        - 22400
        - 22400
        - 22400
validation_station_idx:
    value: -1
validation_train_hours:
    value: 1000
weather_files:
    value:
        - weather_files/Braga_weather.csv
        - weather_files/Lisbon_weather.csv
        - weather_files/Tavira_weather.csv
        - weather_files/Loule_weather.csv
        - weather_files/Faro_weather.csv
        - weather_files/Lisbon_weather.csv
        - weather_files/Setubal_weather.csv
        - weather_files/Lisbon_weather.csv
        - weather_files/Lisbon_weather.csv
